// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using todoapi.Data;

#nullable disable

namespace todoapi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240719065323_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("todoapi.Domain.toDo", b =>
                {
                    b.Property<int>("toDoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("toDoID"));

                    b.Property<bool>("istoDoDone")
                        .HasColumnType("boolean");

                    b.Property<string>("toDoContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("toDoID");

                    b.ToTable("toDoList");
                });
#pragma warning restore 612, 618
        }
    }
}
